// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.AcuerdoNivelServicio", b =>
                {
                    b.Property<int>("SlaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SlaId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<int>("PrioridadId")
                        .HasColumnType("int");

                    b.Property<int>("TiempoResolucionMin")
                        .HasColumnType("int");

                    b.Property<int>("TiempoRespuestaMin")
                        .HasColumnType("int");

                    b.HasKey("SlaId");

                    b.HasIndex("PrioridadId");

                    b.HasIndex("CategoriaId", "PrioridadId")
                        .IsUnique();

                    b.ToTable("AcuerdosNivelServicio", (string)null);

                    b.HasData(
                        new
                        {
                            SlaId = 1,
                            Activo = true,
                            CategoriaId = 1,
                            PrioridadId = 1,
                            TiempoResolucionMin = 60,
                            TiempoRespuestaMin = 15
                        },
                        new
                        {
                            SlaId = 2,
                            Activo = true,
                            CategoriaId = 1,
                            PrioridadId = 2,
                            TiempoResolucionMin = 240,
                            TiempoRespuestaMin = 30
                        },
                        new
                        {
                            SlaId = 3,
                            Activo = true,
                            CategoriaId = 1,
                            PrioridadId = 3,
                            TiempoResolucionMin = 480,
                            TiempoRespuestaMin = 60
                        },
                        new
                        {
                            SlaId = 4,
                            Activo = true,
                            CategoriaId = 2,
                            PrioridadId = 1,
                            TiempoResolucionMin = 60,
                            TiempoRespuestaMin = 15
                        },
                        new
                        {
                            SlaId = 5,
                            Activo = true,
                            CategoriaId = 2,
                            PrioridadId = 2,
                            TiempoResolucionMin = 240,
                            TiempoRespuestaMin = 30
                        },
                        new
                        {
                            SlaId = 6,
                            Activo = true,
                            CategoriaId = 2,
                            PrioridadId = 3,
                            TiempoResolucionMin = 480,
                            TiempoRespuestaMin = 60
                        },
                        new
                        {
                            SlaId = 7,
                            Activo = true,
                            CategoriaId = 2,
                            PrioridadId = 4,
                            TiempoResolucionMin = 1440,
                            TiempoRespuestaMin = 120
                        },
                        new
                        {
                            SlaId = 8,
                            Activo = true,
                            CategoriaId = 3,
                            PrioridadId = 1,
                            TiempoResolucionMin = 60,
                            TiempoRespuestaMin = 15
                        },
                        new
                        {
                            SlaId = 9,
                            Activo = true,
                            CategoriaId = 3,
                            PrioridadId = 2,
                            TiempoResolucionMin = 240,
                            TiempoRespuestaMin = 30
                        },
                        new
                        {
                            SlaId = 10,
                            Activo = true,
                            CategoriaId = 4,
                            PrioridadId = 1,
                            TiempoResolucionMin = 30,
                            TiempoRespuestaMin = 15
                        },
                        new
                        {
                            SlaId = 11,
                            Activo = true,
                            CategoriaId = 4,
                            PrioridadId = 2,
                            TiempoResolucionMin = 120,
                            TiempoRespuestaMin = 20
                        },
                        new
                        {
                            SlaId = 12,
                            Activo = true,
                            CategoriaId = 7,
                            PrioridadId = 3,
                            TiempoResolucionMin = 480,
                            TiempoRespuestaMin = 60
                        },
                        new
                        {
                            SlaId = 13,
                            Activo = true,
                            CategoriaId = 7,
                            PrioridadId = 4,
                            TiempoResolucionMin = 1440,
                            TiempoRespuestaMin = 120
                        });
                });

            modelBuilder.Entity("Domain.Entities.BaseConocimiento", b =>
                {
                    b.Property<int>("ArticuloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArticuloId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<int>("CreadoPorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Problema")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Solucion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ArticuloId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("CreadoPorId");

                    b.ToTable("BaseConocimiento", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoriaId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Categorias", (string)null);

                    b.HasData(
                        new
                        {
                            CategoriaId = 1,
                            Activo = true,
                            Descripcion = "Fallas en equipos físicos: computadoras, impresoras, periféricos",
                            Nombre = "Hardware"
                        },
                        new
                        {
                            CategoriaId = 2,
                            Activo = true,
                            Descripcion = "Errores en aplicaciones, sistemas operativos o instalaciones",
                            Nombre = "Software"
                        },
                        new
                        {
                            CategoriaId = 3,
                            Activo = true,
                            Descripcion = "Problemas de internet, red local, VPN o switches",
                            Nombre = "Red y Conectividad"
                        },
                        new
                        {
                            CategoriaId = 4,
                            Activo = true,
                            Descripcion = "Virus, accesos no autorizados, vulnerabilidades",
                            Nombre = "Seguridad"
                        },
                        new
                        {
                            CategoriaId = 5,
                            Activo = true,
                            Descripcion = "Fallos en cuentas de correo, Outlook o servidor de mail",
                            Nombre = "Correo Electrónico"
                        },
                        new
                        {
                            CategoriaId = 6,
                            Activo = true,
                            Descripcion = "Errores en motores de base de datos o consultas",
                            Nombre = "Base de Datos"
                        },
                        new
                        {
                            CategoriaId = 7,
                            Activo = true,
                            Descripcion = "Solicitudes de acceso, bloqueos de cuenta o cambios de contraseña",
                            Nombre = "Accesos y Permisos"
                        },
                        new
                        {
                            CategoriaId = 8,
                            Activo = true,
                            Descripcion = "Incidencias que no corresponden a las categorías anteriores",
                            Nombre = "Otros"
                        });
                });

            modelBuilder.Entity("Domain.Entities.ComentarioIncidencia", b =>
                {
                    b.Property<int>("ComentarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComentarioId"));

                    b.Property<bool>("EsInterno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("FechaComentario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("IncidenciaId")
                        .HasColumnType("int");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("ComentarioId");

                    b.HasIndex("IncidenciaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ComentariosIncidencia", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.EstadoIncidencia", b =>
                {
                    b.Property<int>("EstadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadoId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("EsEstadoFinal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EstadoId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("EstadosIncidencia", (string)null);

                    b.HasData(
                        new
                        {
                            EstadoId = 1,
                            Descripcion = "Incidencia recibida y pendiente de asignación",
                            EsEstadoFinal = false,
                            Nombre = "Registrado"
                        },
                        new
                        {
                            EstadoId = 2,
                            Descripcion = "Asignado a un técnico, pendiente de atención",
                            EsEstadoFinal = false,
                            Nombre = "Asignado"
                        },
                        new
                        {
                            EstadoId = 3,
                            Descripcion = "El técnico está analizando la causa raíz",
                            EsEstadoFinal = false,
                            Nombre = "En Diagnóstico"
                        },
                        new
                        {
                            EstadoId = 4,
                            Descripcion = "Se está aplicando la solución",
                            EsEstadoFinal = false,
                            Nombre = "En Progreso"
                        },
                        new
                        {
                            EstadoId = 5,
                            Descripcion = "En espera de respuesta del solicitante o de un proveedor",
                            EsEstadoFinal = false,
                            Nombre = "Pendiente"
                        },
                        new
                        {
                            EstadoId = 6,
                            Descripcion = "Solución aplicada, pendiente de confirmación del usuario",
                            EsEstadoFinal = false,
                            Nombre = "Resuelto"
                        },
                        new
                        {
                            EstadoId = 7,
                            Descripcion = "Confirmado y cerrado formalmente",
                            EsEstadoFinal = true,
                            Nombre = "Cerrado"
                        },
                        new
                        {
                            EstadoId = 8,
                            Descripcion = "El usuario reportó que el problema persiste",
                            EsEstadoFinal = false,
                            Nombre = "Reabierto"
                        },
                        new
                        {
                            EstadoId = 9,
                            Descripcion = "Incidencia anulada por el solicitante o administrador",
                            EsEstadoFinal = true,
                            Nombre = "Cancelado"
                        });
                });

            modelBuilder.Entity("Domain.Entities.HistorialIncidencia", b =>
                {
                    b.Property<int>("HistorialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistorialId"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Detalle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoAnterior")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EstadoNuevo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaAccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("IncidenciaId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("HistorialId");

                    b.HasIndex("IncidenciaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("HistorialIncidencias", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Incidencia", b =>
                {
                    b.Property<int>("IncidenciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IncidenciaId"));

                    b.Property<string>("CanalReporte")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<int?>("CerradoPorId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EscaladoAId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEscalamiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaLimiteResolucion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaLimiteRespuesta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaPrimeraRespuesta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaUltimaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<byte>("Impacto")
                        .HasColumnType("tinyint");

                    b.Property<byte>("NumeroReasignaciones")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<string>("NumeroTicket")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PrioridadId")
                        .HasColumnType("int");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<bool>("ResueltoEnPrimerContacto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("SolicitanteId")
                        .HasColumnType("int");

                    b.Property<string>("SolucionAplicada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TecnicoAsignadoId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte>("Urgencia")
                        .HasColumnType("tinyint");

                    b.HasKey("IncidenciaId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("CerradoPorId");

                    b.HasIndex("EscaladoAId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("NumeroTicket")
                        .IsUnique();

                    b.HasIndex("PrioridadId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("SolicitanteId");

                    b.HasIndex("TecnicoAsignadoId");

                    b.HasIndex("FechaRegistro", "FechaResolucion", "FechaCierre")
                        .HasDatabaseName("IX_Incidencias_Fechas");

                    b.ToTable("Incidencias", null, t =>
                        {
                            t.HasCheckConstraint("CK_Incidencia_Impacto", "[Impacto] BETWEEN 1 AND 3");

                            t.HasCheckConstraint("CK_Incidencia_Urgencia", "[Urgencia] BETWEEN 1 AND 3");
                        });
                });

            modelBuilder.Entity("Domain.Entities.NivelPrioridad", b =>
                {
                    b.Property<int>("PrioridadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrioridadId"));

                    b.Property<byte>("Nivel")
                        .HasColumnType("tinyint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TiempoResolucionMin")
                        .HasColumnType("int");

                    b.Property<int>("TiempoRespuestaMin")
                        .HasColumnType("int");

                    b.HasKey("PrioridadId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("NivelesPrioridad", null, t =>
                        {
                            t.HasCheckConstraint("CK_NivelPrioridad_Nivel", "[Nivel] BETWEEN 1 AND 5");
                        });

                    b.HasData(
                        new
                        {
                            PrioridadId = 1,
                            Nivel = (byte)1,
                            Nombre = "Crítico",
                            TiempoResolucionMin = 60,
                            TiempoRespuestaMin = 15
                        },
                        new
                        {
                            PrioridadId = 2,
                            Nivel = (byte)2,
                            Nombre = "Alto",
                            TiempoResolucionMin = 240,
                            TiempoRespuestaMin = 30
                        },
                        new
                        {
                            PrioridadId = 3,
                            Nivel = (byte)3,
                            Nombre = "Medio",
                            TiempoResolucionMin = 480,
                            TiempoRespuestaMin = 60
                        },
                        new
                        {
                            PrioridadId = 4,
                            Nivel = (byte)4,
                            Nombre = "Bajo",
                            TiempoResolucionMin = 1440,
                            TiempoRespuestaMin = 120
                        },
                        new
                        {
                            PrioridadId = 5,
                            Nivel = (byte)5,
                            Nombre = "Planificado",
                            TiempoResolucionMin = 4320,
                            TiempoRespuestaMin = 480
                        });
                });

            modelBuilder.Entity("Domain.Entities.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RolId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            RolId = 1,
                            Descripcion = "Acceso total al sistema",
                            Nombre = "Administrador"
                        },
                        new
                        {
                            RolId = 2,
                            Descripcion = "Gestiona y resuelve incidencias",
                            Nombre = "Técnico"
                        },
                        new
                        {
                            RolId = 3,
                            Descripcion = "Registra y da seguimiento a sus tickets",
                            Nombre = "Solicitante"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("UsuarioId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.AcuerdoNivelServicio", b =>
                {
                    b.HasOne("Domain.Entities.Categoria", "Categoria")
                        .WithMany("AcuerdosNivelServicio")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.NivelPrioridad", "NivelPrioridad")
                        .WithMany("AcuerdosNivelServicio")
                        .HasForeignKey("PrioridadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("NivelPrioridad");
                });

            modelBuilder.Entity("Domain.Entities.BaseConocimiento", b =>
                {
                    b.HasOne("Domain.Entities.Categoria", "Categoria")
                        .WithMany("ArticulosConocimiento")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Entities.Usuario", "CreadoPor")
                        .WithMany("ArticulosCreados")
                        .HasForeignKey("CreadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("CreadoPor");
                });

            modelBuilder.Entity("Domain.Entities.ComentarioIncidencia", b =>
                {
                    b.HasOne("Domain.Entities.Incidencia", "Incidencia")
                        .WithMany("Comentarios")
                        .HasForeignKey("IncidenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Usuario", "Usuario")
                        .WithMany("Comentarios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Incidencia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Entities.HistorialIncidencia", b =>
                {
                    b.HasOne("Domain.Entities.Incidencia", "Incidencia")
                        .WithMany("Historial")
                        .HasForeignKey("IncidenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Usuario", "Usuario")
                        .WithMany("HistorialAcciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Incidencia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Entities.Incidencia", b =>
                {
                    b.HasOne("Domain.Entities.Categoria", "Categoria")
                        .WithMany("Incidencias")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Usuario", "CerradoPor")
                        .WithMany("IncidenciasCerradas")
                        .HasForeignKey("CerradoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.Usuario", "EscaladoA")
                        .WithMany("IncidenciasEscaladas")
                        .HasForeignKey("EscaladoAId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.EstadoIncidencia", "EstadoIncidencia")
                        .WithMany("Incidencias")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.NivelPrioridad", "NivelPrioridad")
                        .WithMany("Incidencias")
                        .HasForeignKey("PrioridadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Usuario", "Solicitante")
                        .WithMany("IncidenciasComoSolicitante")
                        .HasForeignKey("SolicitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Usuario", "TecnicoAsignado")
                        .WithMany("IncidenciasComoTecnico")
                        .HasForeignKey("TecnicoAsignadoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Categoria");

                    b.Navigation("CerradoPor");

                    b.Navigation("EscaladoA");

                    b.Navigation("EstadoIncidencia");

                    b.Navigation("NivelPrioridad");

                    b.Navigation("Solicitante");

                    b.Navigation("TecnicoAsignado");
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.HasOne("Domain.Entities.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Domain.Entities.Categoria", b =>
                {
                    b.Navigation("AcuerdosNivelServicio");

                    b.Navigation("ArticulosConocimiento");

                    b.Navigation("Incidencias");
                });

            modelBuilder.Entity("Domain.Entities.EstadoIncidencia", b =>
                {
                    b.Navigation("Incidencias");
                });

            modelBuilder.Entity("Domain.Entities.Incidencia", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Historial");
                });

            modelBuilder.Entity("Domain.Entities.NivelPrioridad", b =>
                {
                    b.Navigation("AcuerdosNivelServicio");

                    b.Navigation("Incidencias");
                });

            modelBuilder.Entity("Domain.Entities.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.Navigation("ArticulosCreados");

                    b.Navigation("Comentarios");

                    b.Navigation("HistorialAcciones");

                    b.Navigation("IncidenciasCerradas");

                    b.Navigation("IncidenciasComoSolicitante");

                    b.Navigation("IncidenciasComoTecnico");

                    b.Navigation("IncidenciasEscaladas");
                });
#pragma warning restore 612, 618
        }
    }
}
